//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using CapaEntidad;

    public partial class RecursosHumanosEntities : DbContext
    {
        public RecursosHumanosEntities()
            : base("name=RecursosHumanosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Licencia> Licencias { get; set; }
        public virtual DbSet<Nomina> Nominas { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Salida> Salidas { get; set; }
        public virtual DbSet<TotalNomina> TotalNominas { get; set; }
        public virtual DbSet<Vacacione> Vacaciones { get; set; }
    
        public virtual ObjectResult<BuscarEmpleadoActivoPorNombre_Result> BuscarEmpleadoActivoPorNombre(string empleado)
        {
            var empleadoParameter = empleado != null ?
                new ObjectParameter("Empleado", empleado) :
                new ObjectParameter("Empleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarEmpleadoActivoPorNombre_Result>("BuscarEmpleadoActivoPorNombre", empleadoParameter);
        }
    }
}
