//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida
    {
        public int ID { get; set; }
        public Nullable<int> Empleado { get; set; }
        public string Tipo { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> FechadeSalida { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
    }
}
